# -*- coding: utf-8 -*-
"""fibonacci no. code.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZUaap1cosuL5cWkb6QACzIttWHxHAd3h
"""

n= 15
#fibonacci no. = fb
fb=[0,1]

for i in range (2,n):
  fb += [fb[-1] + fb[-2]]

print("first n fibonacci no.s are:", fb)