# -*- coding: utf-8 -*-
"""python code to print positive no.s in a list.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1503pbwmoUHmSF16nhIEa0Sc_0o7Fn6uc
"""

l1=[11,-32,34,-23,41]
l2=[]
for i in l1:
  if i >0:
    l2.append(i)
print("inout",l1)
print("output",l2)