# -*- coding: utf-8 -*-
"""python code 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQSzmozw1OcFbODTQ4zs-0rNPPQkmy6l
"""



print("Hello World")